[package]
name = "rust-lambda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.5.1"
tokio="*"
serde_json="*"
lambda_http="*"

[[bin]]
name="bootstrap"
path="src/main.rs"
